In [ ]:
#Pandas Read CSV:A simple way to store big data sets is to use CSV files (comma separated files).
#CSV files contains plain text and is a well know format that can be read by everyone including Pandas.
#In our examples we will be using a CSV file called 'data.csv'.

In [39]:
import pandas as pd
df = pd.read_csv('C:\\Users\\Dell\\Desktop\\data.csv')
print(df.to_string()) 

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

In [40]:
#Print the DataFrame without the to_string() method:
import pandas as pd
df = pd.read_csv('C:\\Users\\Dell\\Desktop\\data.csv')
print(df) 

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


In [41]:
#Check the number of maximum returned rows:
import pandas as pd
print(pd.options.display.max_rows) 

60


In [42]:
#Increase the maximum number of rows to display the entire DataFrame:
import pandas as pd
pd.options.display.max_rows = 9999
df = pd.read_csv('C:\\Users\\Dell\\Desktop\\data.csv')
print(df) 

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

In [43]:
#dataframe read xlsx.file
df = pd.read_excel('C:\\Users\\Dell\\Desktop\\data.xlsx')
print(df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

In [46]:
#Create DataFrame from Dictionary using  pandas.
# import pandas library
import pandas as pd
# dictionary with list object in values
details = {
    'Name' : ['Ankit', 'Aishwarya', 'Shaurya', 'Shivangi'],
    'Age' : [23, 21, 22, 21],
    'University' : ['BHU', 'JNU', 'DU', 'BHU'],
}
# creating a Dataframe object 
df = pd.DataFrame(details)
df

Name  Age University
0      Ankit   23        BHU
1  Aishwarya   21        JNU
2    Shaurya   22         DU
3   Shivangi   21        BHU

In [47]:
#Create DataFrame from Dictionary with user-defined indexes.
# import pandas library
import pandas as pd
# dictionary with list object in values
details = {
    'Name' : ['Ankit', 'Aishwarya', 'Shaurya', 'Shivangi'],
    'Age' : [23, 21, 22, 21],
    'University' : ['BHU', 'JNU', 'DU', 'BHU'],
}
# creating a Dataframe object from dictionary 
# with custom indexing
df = pd.DataFrame(details, index = ['a', 'b', 'c', 'd'])
df

Name  Age University
a      Ankit   23        BHU
b  Aishwarya   21        JNU
c    Shaurya   22         DU
d   Shivangi   21        BHU

In [50]:
#Create DataFrame from Dictionary with required columns only
# import pandas library
import pandas as pd
# dictionary with list object in values
details = {
    'Name' : ['Ankit', 'Aishwarya', 'Shaurya', 'Shivangi'],
    'Age' : [23, 21, 22, 21],
    'University' : ['BHU', 'JNU', 'DU', 'BHU'],
}
# creating a Dataframe object with skipping 
# one column i.e skipping age column.
df = pd.DataFrame(details, columns = ['Name', 'University'])
df

Name University
0      Ankit        BHU
1  Aishwarya        JNU
2    Shaurya         DU
3   Shivangi        BHU

In [51]:
#Create DataFrame from nested Dictionary
# import pandas library
import pandas as pd
# dictionary with dictionary object
# in values i.e. nested dictionary
details = { 
    0 : {
        'Name' : 'Ankit',
        'Age' : 22,
        'University' : 'BHU'
        },
    1 : {
        'Name' : 'Aishwarya',
        'Age' : 21,
        'University' : 'JNU'
        },
    2 : {
        'Name' : 'Shaurya',
        'Age' : 23,
        'University' : 'DU'
        }
}
df = pd.DataFrame(details)
df = df.transpose()
df

Name Age University
0      Ankit  22        BHU
1  Aishwarya  21        JNU
2    Shaurya  23         DU

In [52]:
# dataframe create using matrix
import pandas as pd
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})
matrix = df.values
print(matrix)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [53]:
import pandas as pd
df2 = pd.DataFrame({
    'X': [0.1, 0.2, 0.3],
    'Y': [0.4, 0.5, 0.6],
    'Z': [0.7, 0.8, 0.9]
})
matrix2 = df2.to_numpy()
print(matrix2)

[[0.1 0.4 0.7]
 [0.2 0.5 0.8]
 [0.3 0.6 0.9]]


In [54]:
import pandas as pd
import numpy as np
df3 = pd.DataFrame({
    'P': [10, 20, 30],
    'Q': [40, 50, 60],
    'R': [70, 80, 90]
})
matrix3 = np.asarray(df3)
print(matrix3)

[[10 40 70]
 [20 50 80]
 [30 60 90]]


In [57]:
#Use Series.as_matrix() function to return the numpy-array representation of the given series object.
# importing pandas as pd 
import pandas as pd 
# Creating the Series 
sr = pd.Series(['New York', 'Chicago', 'Toronto', 'Lisbon', 'Rio'])  
# Create the Index 
index_ = ['City 1', 'City 2', 'City 3', 'City 4', 'City 5']   
# set the index 
sr.index = index_  
# Print the series 
print(sr) 

City 1    New York
City 2     Chicago
City 3     Toronto
City 4      Lisbon
City 5         Rio
dtype: object
